<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>NU1900</NoWarn>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.11" />
    <PackageReference Include="dbup-core" Version="6.1.1" />
    <PackageReference Include="dbup-postgresql" Version="7.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TaindSoft.Core.Application\TaindSoft.Core.Application.csproj" />
    <ProjectReference Include="..\TaindSoft.Core.Domain\TaindSoft.Core.Domain.csproj" />
    <ProjectReference Include="..\TaindSoft.Core\TaindSoft.Core.csproj" />
  </ItemGroup>

</Project>


