using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TaindSoft.Core.Domain.Entities
{
    /// <summary>
    /// Base class for all domain entities
    /// Id: Int32 primary key, auto-increment (for performance)
    /// Guid: UUID unique identifier (for external reference, hides primary key)
    /// </summary>
    public abstract class Entity
    {
        /// <summary>
        /// Primary key, auto-incremented by the database. Used for internal references and relationships.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; protected set; }

        /// <summary>
        /// Globally unique identifier for the entity. Used for external references, API contracts, and to avoid exposing internal IDs.
        /// </summary>
        public Guid Guid { get; protected set; }

        /// <summary>
        /// Default constructor for new entities (Id will be generated by database, Guid is auto-generated)
        /// </summary>
        public Entity()
        {
            Id = 0;
            Guid = Guid.NewGuid();
        }

        /// <summary>
        /// Equality based on type and Id (ignores Guid). Two entities are equal if they are of the same type and have the same Id.
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public override bool Equals(object? obj)
        {
            return obj is Entity entity && entity.GetType() == GetType() && entity.Id == Id;
        }

        /// <summary>
        /// Hash code based on Id. This is important for collections and dictionaries. Two entities with the same Id will have the same hash code.
        /// </summary>
        /// <returns></returns>
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }

}
